AWSTemplateFormatVersion: 2010-09-09
Description: Creates the IAM Role and KMS CMK for the EBS Encryption Remediation Process
Parameters: 
  KeyAdminParameter:
    Description: ARN of Key Admin IAM User or Role
    Type: String
Resources: 
  EncryptionRemediationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - ssm.amazonaws.com
                - Fn::Join:
                    - ""
                    - - ec2.
                      - Ref: AWS::URLSuffix
        Version: "2012-10-17"
      ManagedPolicyArns:
        - !Ref EncryptEBSAutomationRolePolicy
  EncryptEBSAutomationRolePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument: 
        Statement:
          - Action:
            - cloudformation:CreateStack
            - cloudformation:DescribeStacks
            - cloudformation:DeleteStack
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ''
                  - - 'arn:aws:cloudformation:'
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - ":stack/DetachEBSVolumeStack*"
              - Fn::Join:
                  - ''
                  - - 'arn:aws:cloudformation:'
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - ":stack/AttachEBSVolumeStack*"
          - Action:
            - ec2:AttachVolume
            - ec2:CopySnapshot
            - ec2:CreateSnapshot
            - ec2:CreateVolume
            - ec2:CreateTags
            - ec2:DeleteSnapshot
            - ec2:DeleteVolume
            - ec2:DescribeInstances
            - ec2:DescribeInstanceStatus
            - ec2:DescribeNetworkInterfaces
            - ec2:DescribeSnapshots
            - ec2:DescribeVolumes
            - ec2:ModifyInstanceAttribute
            - ec2:StartInstances
            - ec2:StopInstances
            - tag:TagResources
            Effect: Allow
            Resource: "*"
          - Action:
            - lambda:DeleteFunction
            - lambda:CreateFunction
            - lambda:GetFunction*
            - lambda:InvokeFunction
            Effect: Allow
            Resource:
              Fn::Join:
              - ''
              - - 'arn:aws:lambda:'
                - Ref: AWS::Region
                - ":"
                - Ref: AWS::AccountId
                - ":function:DetachVolumeLambda*"
          - Action:
            - ssm:GetAutomationExecution
            - ssm:StartAutomationExecution
            Effect: Allow
            Resource: "*"
          - Action:
            - kms:Encrypt
            - kms:Decrypt
            - kms:ReEncrypt*
            - kms:GenerateDataKey*
            - kms:CreateGrant
            - kms:ListGrants
            - kms:DescribeKey
            Effect: Allow
            Resource: "*"
          - Action: iam:PassRole
            Effect: Allow
            Resource:
              Fn::Join:
              - ''
              - - 'arn:aws:iam::'
                - Ref: AWS::AccountId
                - ":role/DetachEBSVolumeStack*LambdaRole*"
          - Action:
            - iam:DeleteRole
            - iam:PutRolePolicy*
            - iam:GetRole*
            - iam:CreateRole
            - iam:DeleteRolePolicy
            Effect: Allow
            Resource:
              Fn::Join:
              - ''
              - - 'arn:aws:iam::'
                - Ref: AWS::AccountId
                - ":role/DetachEBSVolumeStack*LambdaRole*"
        Version: '2012-10-17'

  EBSEncryptionCMK:
    Type: AWS::KMS::Key
    Properties: 
      Description: CMK used for encryption EBS volumes
      Enabled: True
      EnableKeyRotation: True
      KeyPolicy: 
        Version: '2012-10-17'
        Id: key-default-1
        Statement:
        - Sid: Enable IAM User Permissions
          Effect: Allow
          Principal:
            AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
          Action: kms:*
          Resource: '*'
        - Sid: Allow administration of the key
          Effect: Allow
          Principal:
            AWS: !Ref KeyAdminParameter
          Action:
          - kms:Create*
          - kms:Describe*
          - kms:Enable*
          - kms:List*
          - kms:Put*
          - kms:Update*
          - kms:Revoke*
          - kms:Disable*
          - kms:Get*
          - kms:Delete*
          - kms:ScheduleKeyDeletion
          - kms:CancelKeyDeletion
          Resource: '*'
        - Sid: Allow use of the key
          Effect: Allow
          Principal:
            AWS: !GetAtt EncryptionRemediationRole.Arn
          Action:
          - kms:DescribeKey
          - kms:Encrypt
          - kms:Decrypt
          - kms:ReEncrypt*
          - kms:GenerateDataKey
          - kms:GenerateDataKeyWithoutPlaintext
          Resource: '*'
  EBSEncryptionCMKAlias:
    Type: AWS::KMS::Alias
    Properties: 
      AliasName: alias/EC2EncryptionAtRestCMKAlias
      TargetKeyId: !Ref EBSEncryptionCMK
Outputs:
  RoleARN:
    Description: ARN of the EncryptionRemediationRole
    Value: !GetAtt EncryptionRemediationRole.Arn
    Export: 
      Name: !Sub "${AWS::StackName}-RoleARN"
  CMKID:
    Description: Key ID of EBSEncryptionCMK
    Value: !Ref EBSEncryptionCMK
    Export: 
      Name: !Sub "${AWS::StackName}-CMKID"